runtime: java
env: flex
runtime_config:
  jdk: openjdk17
handlers:
  - url: /.*
    script: auto
manual_scaling:
  instances: 1

network:
  name: projects/ashiph/global/networks/my-vpc
  instance_ip_mode: internal
#  instance_tag: private-service
  forwarded_ports:
    - 3306/tcp

#Resource Settings
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
#  volumes:
#    - name: ramdisk1
#      volume_type: tmpfs
#      size_gb: 0.5

#  Only accept traffic from the internal VPC
#network:
#  instance_tag: private-service


#env_varaibles:
#  CLOUD_SQL_USERNAME: root
#  CLOUD_SQL_PASSWORD: root
#  CLOUD_SQL_DATABASE_NAME: user_management
#  CLOUD_SQL_CONNECTION_NAME: ashiph:us-central1:gcp-mysql

vpc_access_connector:
  name: projects/ashiph/locations/us-central1/connectors/connector-user-management

